blank_issues_enabled: false
contact_links:
  - name: 🔮 Discord
    url: https://discord.com/users/110107013207306240
    about: Message me on Discord for any questions, suggestions, or just to say hi!
